name: crop_weather
version: '1.0'
profile: crop_pipeline
config-version: 2
seed-paths: ["seeds"]
model-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
